apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: carreviewbackendnestjs
  name: carreviewbackendnestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carreviewbackendnestjs
  template:
    metadata:
      labels:
        app: carreviewbackendnestjs
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
    spec:
      containers:
      - image: sreyansh/carreviewbackendnestjs
        name: carreviewbackendnestjs
        ports:
        - containerPort: 3000